#!/bin/sh /etc/rc.common

START=95
STOP=10

USE_PROCD=1
PROG=/usr/sbin/jp-ipoe-setup

start_service() {
	local enabled
	config_load jp_ipoe
	config_get enabled config enabled 0
	[ "$enabled" = "1" ] || return 0

	procd_open_instance
	procd_set_param command "$PROG" start
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	/usr/sbin/jp-ipoe-setup stop
}

service_triggers() {
	procd_add_reload_trigger "jp_ipoe"
}
